branch-defaults:
  development:
    environment: modart-env
environment-defaults:
  modart-env:
    branch: null
    repository: null
global:
  application_name: modart-app
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
