version : '3'
services:
  server:
    container_name: modart-server
    build:
      context: .
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - .:/modart-server
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}


  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
   

volumes:
  api:
  database_postgres: 
