version : '3'
services:
  api:
    container_name: modart
    build:
      context: ./modart-server
    ports:
      - 5000:5000
    networks:
      - modart-net
    restart: on-failure
    volumes:
      - .:/api
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}

  client:
    build:
      context: ./modart-client
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
   

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - 5432:5432
    networks:
      - modart-net
    volumes:
      - database_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}

volumes:
  api:
  database_postgres: 

networks:
  modart-net:
    driver: bridge
