version : '3'
services:
  server:
    container_name: modart-server
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - modart-net
    restart: on-failure
    volumes:
      - .:/server
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST2}
      - DATABASE_PORT=${DB_PORT}

  client:
      build:
        context: ./client
      container_name: modart-client
      ports:
        - 3000:3000
      volumes:
        - ./client:/client/client
        - /client/app/node_modules
      networks:
        - modart-net
   

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - 5432:5432
    networks:
      - modart-net
    volumes:
      - database_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}

volumes:
  api:
  database_postgres: 

networks:
  modart-net:
    driver: bridge
