version : '3'
services:
  server:
    container_name: modart-server
    build:
      context: .
    ports:
      - 5000:5000
    networks:
      - modart-net
    restart: on-failure
    volumes:
      - .:/modart-server
    depends_on:
      - modart-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST2}
      - DATABASE_PORT=${DB_PORT}

  modart-postgres:
    image: postgres:latest
    container_name: modart-postgres
    ports:
      - 5432:5432
    networks:
      - modart-net
    volumes:
      - database_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}

volumes:
  api:
  database_postgres: 

networks:
  modart-net:
    driver: bridge
